
 //Custom Text Header //
 // ACSII slant font

// Needs to be inside <section id="login" class="shadow">
// YOU MUST ESCAPE ANY SINGLE BACKSLASHES LIKE SO: \\

let custom_text_header = `
<div class="custom-text-header"> <pre>                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                        
EEEEEEEEEEEEEEEEEEEEEE                    kkkkkkkk                                                         tttt          EEEEEEEEEEEEEEEEEEEEEE                                                          iiii                                                                                iiii                                       
E::::::::::::::::::::E                    k::::::k                                                      ttt:::t          E::::::::::::::::::::E                                                         i::::i                                                                              i::::i                                      
E::::::::::::::::::::E                    k::::::k                                                      t:::::t          E::::::::::::::::::::E                                                          iiii                                                                                iiii                                       
EE::::::EEEEEEEEE::::E                    k::::::k                                                      t:::::t          EE::::::EEEEEEEEE::::E                                                                                                                                                                                         
  E:::::E       EEEEEE    cccccccccccccccc k:::::k    kkkkkkk eeeeeeeeeeee    rrrrr   rrrrrrrrr   ttttttt:::::ttttttt      E:::::E       EEEEEEnnnn  nnnnnnnn       ggggggggg   gggggnnnn  nnnnnnnn    iiiiiiinnnn  nnnnnnnn        eeeeeeeeeeee        eeeeeeeeeeee    rrrrr   rrrrrrrrr  iiiiiiinnnn  nnnnnnnn       ggggggggg   ggggg
  E:::::E               cc:::::::::::::::c k:::::k   k:::::kee::::::::::::ee  r::::rrr:::::::::r  t:::::::::::::::::t      E:::::E             n:::nn::::::::nn    g:::::::::ggg::::gn:::nn::::::::nn  i:::::in:::nn::::::::nn    ee::::::::::::ee    ee::::::::::::ee  r::::rrr:::::::::r i:::::in:::nn::::::::nn    g:::::::::ggg::::g
  E::::::EEEEEEEEEE    c:::::::::::::::::c k:::::k  k:::::ke::::::eeeee:::::eer:::::::::::::::::r t:::::::::::::::::t      E::::::EEEEEEEEEE   n::::::::::::::nn  g:::::::::::::::::gn::::::::::::::nn  i::::in::::::::::::::nn  e::::::eeeee:::::ee e::::::eeeee:::::eer:::::::::::::::::r i::::in::::::::::::::nn  g:::::::::::::::::g
  E:::::::::::::::E   c:::::::cccccc:::::c k:::::k k:::::ke::::::e     e:::::err::::::rrrrr::::::rtttttt:::::::tttttt      E:::::::::::::::E   nn:::::::::::::::ng::::::ggggg::::::ggnn:::::::::::::::n i::::inn:::::::::::::::ne::::::e     e:::::ee::::::e     e:::::err::::::rrrrr::::::ri::::inn:::::::::::::::ng::::::ggggg::::::gg
  E:::::::::::::::E   c::::::c     ccccccc k::::::k:::::k e:::::::eeeee::::::e r:::::r     r:::::r      t:::::t            E:::::::::::::::E     n:::::nnnn:::::ng:::::g     g:::::g   n:::::nnnn:::::n i::::i  n:::::nnnn:::::ne:::::::eeeee::::::ee:::::::eeeee::::::e r:::::r     r:::::ri::::i  n:::::nnnn:::::ng:::::g     g:::::g 
  E::::::EEEEEEEEEE   c:::::c              k:::::::::::k  e:::::::::::::::::e  r:::::r     rrrrrrr      t:::::t            E::::::EEEEEEEEEE     n::::n    n::::ng:::::g     g:::::g   n::::n    n::::n i::::i  n::::n    n::::ne:::::::::::::::::e e:::::::::::::::::e  r:::::r     rrrrrrri::::i  n::::n    n::::ng:::::g     g:::::g 
  E:::::E             c:::::c              k:::::::::::k  e::::::eeeeeeeeeee   r:::::r                  t:::::t            E:::::E               n::::n    n::::ng:::::g     g:::::g   n::::n    n::::n i::::i  n::::n    n::::ne::::::eeeeeeeeeee  e::::::eeeeeeeeeee   r:::::r            i::::i  n::::n    n::::ng:::::g     g:::::g 
  E:::::E       EEEEEEc::::::c     ccccccc k::::::k:::::k e:::::::e            r:::::r                  t:::::t    tttttt  E:::::E       EEEEEE  n::::n    n::::ng::::::g    g:::::g   n::::n    n::::n i::::i  n::::n    n::::ne:::::::e           e:::::::e            r:::::r            i::::i  n::::n    n::::ng::::::g    g:::::g 
EE::::::EEEEEEEE:::::Ec:::::::cccccc:::::ck::::::k k:::::ke::::::::e           r:::::r                  t::::::tttt:::::tEE::::::EEEEEEEE:::::E  n::::n    n::::ng:::::::ggggg:::::g   n::::n    n::::ni::::::i n::::n    n::::ne::::::::e          e::::::::e           r:::::r           i::::::i n::::n    n::::ng:::::::ggggg:::::g 
E::::::::::::::::::::E c:::::::::::::::::ck::::::k  k:::::ke::::::::eeeeeeee   r:::::r                  tt::::::::::::::tE::::::::::::::::::::E  n::::n    n::::n g::::::::::::::::g   n::::n    n::::ni::::::i n::::n    n::::n e::::::::eeeeeeee   e::::::::eeeeeeee   r:::::r           i::::::i n::::n    n::::n g::::::::::::::::g 
E::::::::::::::::::::E  cc:::::::::::::::ck::::::k   k:::::kee:::::::::::::e   r:::::r                    tt:::::::::::ttE::::::::::::::::::::E  n::::n    n::::n  gg::::::::::::::g   n::::n    n::::ni::::::i n::::n    n::::n  ee:::::::::::::e    ee:::::::::::::e   r:::::r           i::::::i n::::n    n::::n  gg::::::::::::::g 
EEEEEEEEEEEEEEEEEEEEEE    cccccccccccccccckkkkkkkk    kkkkkkk eeeeeeeeeeeeee   rrrrrrr                      ttttttttttt  EEEEEEEEEEEEEEEEEEEEEE  nnnnnn    nnnnnn    gggggggg::::::g   nnnnnn    nnnnnniiiiiiii nnnnnn    nnnnnn    eeeeeeeeeeeeee      eeeeeeeeeeeeee   rrrrrrr           iiiiiiii nnnnnn    nnnnnn    gggggggg::::::g 
                                                           
</pre> </div>
`;
document.getElementById("login").innerHTML += custom_text_header
